### ISSUE TITLE
Installation failed, libunwind.h not available

### ISSUE THREAD

**Issue by mrocklin** [numba/stacktrace#1]
```
mrocklin@carbon:~/workspace$ conda install -c defaults -c conda-forge libunwind

mrocklin@carbon:~/workspace/stacktrace$ python setup.py install
running install
running build
running build_ext
building 'stacktrace._bt' extension
gcc -pthread -B /home/mrocklin/Software/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mrocklin/Software/anaconda/include/python3.6m -c stacktrace/bt.c -o build/temp.linux-x86_64-3.6/stacktrace/bt.o
stacktrace/bt.c:12:23: fatal error: libunwind.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by sklam** [comment]
Are you running on Linux?  I've not tested on it yet.

**Comment by mrocklin** [comment]
Yes

**Comment by ogrisel** [comment]
I worked around this problem by using a system install of libunwind: `sudo apt install libunwind-dev`.

<del>But then I faced #2</del>. [now fixed].

**Comment by ogrisel** [comment]
The `Extension` does not link against the unwind library. I think it's required, no?

```diff
diff --git a/setup.py b/setup.py
index d7313df..a8342da 100644
--- a/setup.py
+++ b/setup.py
@@ -1,7 +1,8 @@
 from distutils.core import setup, Extension
 
 
-module_bt = Extension('stacktrace._bt', sources=['stacktrace/bt.c'])
+module_bt = Extension('stacktrace._bt', sources=['stacktrace/bt.c'],
+                      libraries=['unwind'])
 
 with open('README.md') as fin:
     readmetext = fin.read()
```

**Comment by ogrisel** [comment]
After fixing this I can build but I get invalid output from libunwind-1.2.1:

```python-traceback
$ python test_simple.py 
Traceback (most recent call last):
  File "test_simple.py", line 3, in <module>
    print_stack()
  File "/home/ogrisel/code/stacktrace/stacktrace/basic.py", line 18, in print_stack
    rawtrace = buf[:outsz].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 0: ordinal not in range(128)
```

The extension seems to link correctly against the libunwind library from my dedicated conda env:

```
$ ldd stacktrace/_bt.cpython-36m-x86_64-linux-gnu.so 
	linux-vdso.so.1 =>  (0x00007ffc30f62000)
	libunwind.so.8 => /home/ogrisel/miniconda3/envs/stacktrace/lib/libunwind.so.8 (0x00007effff7c2000)
	libpython3.6m.so.1.0 => /home/ogrisel/miniconda3/envs/stacktrace/lib/libpython3.6m.so.1.0 (0x00007effff286000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007effff069000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efffec9f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007effffbfe000)
	libgcc_s.so.1 => /home/ogrisel/miniconda3/envs/stacktrace/lib/./libgcc_s.so.1 (0x00007effffdea000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efffea9b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007efffe898000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007efffe690000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efffe387000)
```

**Comment by ogrisel** [comment]
Actually here is a more complete fix for the setup.py to ensure that the `_bt.c` extension module builds against the `libunwind.h` provided by a conda env:

```diff
diff --git a/setup.py b/setup.py
index d7313df..6d4db14 100644
--- a/setup.py
+++ b/setup.py
@@ -1,7 +1,19 @@
 from distutils.core import setup, Extension
+import sys
+import os.path as op
 
 
-module_bt = Extension('stacktrace._bt', sources=['stacktrace/bt.c'])
+def get_include_dirs():
+    include_dir = op.normpath(op.join(sys.executable, '..', '..', 'include'))
+    if op.exists(op.join(include_dir, 'libunwind.h')):
+        # If libunwind was installed in a conda environment, the headers
+        # should be there.
+        return [include_dir]
+    return []
+
+
+module_bt = Extension('stacktrace._bt', sources=['stacktrace/bt.c'],
+                      include_dirs=get_include_dirs(),   libraries=['unwind'])
 
 with open('README.md') as fin:
     readmetext = fin.read()
```

**Comment by ogrisel** [comment]
It seems to work as expected in the current master. This issue can be closed.
