### ISSUE TITLE
Missing stacktrace.basic module?

### ISSUE THREAD

**Issue by ogrisel** [numba/stacktrace#2]
```python-traceback
$ python test_simple.py 
Traceback (most recent call last):
  File "test_simple.py", line 1, in <module>
    from stacktrace.basic import print_stack
  File "/home/ogrisel/code/stacktrace/stacktrace/__init__.py", line 1, in <module>
    from stacktrace.basic import (
ModuleNotFoundError: No module named 'stacktrace.basic'
```

```bash
$ ls stacktrace
bt.c                                 core.py      __pycache__  utils.py
_bt.cpython-37m-x86_64-linux-gnu.so  __init__.py  timer.py
```

**Comment by ogrisel** [comment]
Fixed by 5427fc16dd35eea0eddc4f8c98a7763262ad5cf0.
